version: 2.1
orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - run:
          name: ip
          command: echo $HOSTNAME
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Install FFMPEG
          command: sudo apt-get install -y ffmpeg
      - run:
          name: Install
          command: yarn
      - run:
          name: start dgit
          command: export CI=true && yarn start &
      - run:
          name: wait on dgit
          command: sleep 10
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  e2e-test:
    jobs:
      - test